version: 0.1

phases:

  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/0.14.10/terraform_0.14.10_linux_amd64.zip"
      - "unzip terraform_0.14.10_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"

  build:
    commands:
      - terraform init
      - terraform validate
      - terraform fmt -recursive
      - "terraform apply --auto-approve"

